CLWebApp/CLWebApp/Models/ViewModels/Practice2ViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CLWebApp.Models.ViewModels
{
    public class Practice2ViewModel
    {
        /// <summary>
        /// 勝利数
        /// </summary>
        [Required(ErrorMessage = "勝利数を入力してください")]
        [RegularExpression(@"[0-9]+", ErrorMessage = "勝利数は正の整数を入力してください")]
        [Display(Name = "勝利数：")]
        public string Victory { get; set; }

        /// <summary>
        /// 敗戦数
        /// </summary>
        [Required(ErrorMessage = "敗戦数を入力してください")]
        [RegularExpression(@"[0-9]+", ErrorMessage = "敗戦数は正の整数を入力してください")]
        [Display(Name = "敗戦数：")]
        public string Defeat { get; set; }

        /// <summary>
        /// 引き分け
        /// </summary>
        // [Required(ErrorMessage = "引き分け数を入力してください")]
        [RegularExpression(@"[0-9]+", ErrorMessage = "引き分け数は正の整数を入力してください")]
        [Display(Name = "引き分け数：")]
        public string Draw { get; set; }

        /// <summary>
        /// 勝率
        /// </summary>
        [Display(Name = "勝率：")]
        public string Winning { get; set; }

        /// <summary>
        /// 計算完了判定
        /// </summary>
        public bool isCalculated { get; set; }

    }
}

CLWebApp/CLWebApp/Controllers/AverageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CLWebApp.Models.ViewModels;
using CLWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CLWebApp.Controllers
{

    /// <summary>
    /// 打率計算画面コントローラー
    /// </summary>
    [Authorize]
    public class AverageController : Controller
    {
        // 打率計算サービス
        private AverageService _service;

        /// <summary>
        /// コンストラクター
        /// </summary>
        public AverageController()
        {
           _service = new AverageService();
        }

        /// <summary>
        /// 画面初期表示
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            AverageViewModel model = new AverageViewModel();
            // 画面初期化
            _service.Clear(model);
            return View(model);
        }

        /// <summary>
        /// 計算処理
        /// </summary>
        /// <param name="model">打率計算画面ViewModel</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Calc(AverageViewModel model)
        {
            if (ModelState.IsValid)
            {
                string batsVal = model.Bats;
                string hitsVal = model.Hits;
                bool chkMou = model.Mou;

                // 入力チェック結果を取得
                string message = _service.InputCheck(batsVal, hitsVal);

                // ⇒入力チェックの結果、エラーがあればメッセージをダイアログに出して処理終了
                if (!string.IsNullOrWhiteSpace(message))
                {
                    //MessageBox.Show(message);
                    //return;
                    // エラーの場合
                    ModelState.AddModelError(string.Empty, message);
                }
                else
                {
                    // 打数がゼロの場合、"-" を表示
                    if ("0".Equals(batsVal))
                    {
                        model.Average = "-";
                    }
                    // 打数がゼロ以外の場合
                    // 打率計算を実施       
                    else
                    {
                        // 打数,安打数を数値変換 ※入力値チェックが完了しているので数値変換時のエラーの心配なし
                        double batsDoubleVal = double.Parse(batsVal);
                        double hitsDoubleVal = double.Parse(hitsVal);

                        // 打率計算結果を取得
                        double averageVal = _service.CalcAverage(batsDoubleVal, hitsDoubleVal, chkMou);

                        // 打率表示整形メソッドの結果をstring型に代入
                        string aveCharacterString = _service.AveFormat(averageVal, chkMou);
                        // 打率表示テキストボックスのテキストに代入
                        model.Average = aveCharacterString;
                    }
                }
            }
            return View("Index",model);
        }
    }
}

CLWebApp/CLWebApp/Controllers/Practice2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CLWebApp.Data;
using CLWebApp.Models;
using CLWebApp.Models.ViewModels;
using CLWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CLWebApp.Controllers
{
    /// <summary>
    /// 勝率計算画面コントローラー
    /// </summary>
    [Authorize]
    public class Practice2Controller : CLBaseController
    {
        private readonly ApplicationDbContext _context;
        private Practice2Service _service;
        private List<ParkingInfo> _parkingInfoList = new List<ParkingInfo>();


        /// <summary>
        /// コンストラクタ
        /// </summary>
        public Practice2Controller(ApplicationDbContext context)
        {
            _service = new Practice2Service();
            _context = context;
            // パーキング情報DBからデータを取り出す
            _parkingInfoList = _context.ParkingInfos.ToList();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Winning()
        {
            Practice2ViewModel model = new Practice2ViewModel();
            // 画面初期化
            _service.Clear(model);

            return View(model);
        }


        /// <summary>
        /// 駐車場情報初期表示
        /// </summary>
        /// <returns></returns>
        public IActionResult ParkingRecordCreate()
        {
            // 駐車場情報リスト設定
            SetParkingInfoSelectListToViewBag();
            return View();
        }


        // POST: Home/Index
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(Practice2ViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (viewModel.Victory == "")
                {
                    // エラーの場合
                    ModelState.AddModelError(string.Empty, "勝利数を入力してください");
                }
                else
                {
                    // 正常の場合
                    return RedirectToAction("Winning");
                }
            }
            return View(viewModel);
        }


        /// <summary>
        /// 計算処理
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Calc(Practice2ViewModel model)
        {
            if (ModelState.IsValid)
            {
                string victoryString = model.Victory;
                string defeatString = model.Defeat;
                string drawString = model.Draw;

                double victorydouble = double.Parse(model.Victory);
                double defeatdouble = double.Parse(model.Defeat);

                //// 入力チェックを行う
                //// 入力チェック結果を取得
                string message = _service.InputCheck(victoryString,defeatString);
                if (!string.IsNullOrWhiteSpace(message))
                {
                    // エラーの場合
                    ModelState.AddModelError(string.Empty, message);
                }
                else
                {
                    // 勝利数、敗戦数、引き分け数がゼロの場合、"-" を表示
                    if (victorydouble == 0 && defeatdouble == 0 && defeatdouble == 0)
                    {
                        model.Winning = "-";
                    }
                    else
                    {
                        // 勝率を計算
                        double winningDouble = _service.WinPercentagealcalc(victorydouble, defeatdouble);

                        // 試合数があり、勝利数がゼロの場合、".000" を表示
                        if (victorydouble == 0)
                        {
                            model.Winning = ".000";
                        }
                        else
                        {
                            //// 計算結果をテキストボックスにセット
                            model.Winning = winningDouble.ToString("F3");

                        }
                    }
                }
            }
            ////// 計算結果をテキストボックスにセット
            return View("Winning", model);
        }


        /// <summary>
        /// 計算処理(Ajax)
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult CalcAjax(Practice2ViewModel model)
        {
                string victoryString = model.Victory;
                string defeatString = model.Defeat;
                string drawString = model.Draw;
                string winningStr = "";

                //// 入力チェックを行う
                //// 入力チェック結果を取得
                string message = _service.InputCheck(victoryString, defeatString);
                if (!string.IsNullOrWhiteSpace(message))
                {
                    // エラーの場合
                    // ModelState.AddModelError(string.Empty, message);

                    // 処理結果がエラーであることとexceptionメッセージをJsonで返却
                    return Json(new
                    {
                        status = "Error",
                        message = "入力してください"
                    });

                }
                else
                {
                    double victorydouble = double.Parse(model.Victory);
                    double defeatdouble = double.Parse(model.Defeat);

                    // 勝利数、敗戦数、引き分け数がゼロの場合、"-" を表示
                    if (victorydouble == 0 && defeatdouble == 0 && defeatdouble == 0)
                    {
                        winningStr  = "-";
                    }
                    else
                    {
                        // 勝率を計算
                        double winningDouble = _service.WinPercentagealcalc(victorydouble, defeatdouble);

                        // 試合数があり、勝利数がゼロの場合、".000" を表示
                        if (victorydouble == 0)
                        {
                            winningStr = ".000";
                        }
                        else
                        {
                            //// 計算結果をテキストボックスにセット
                            winningStr = winningDouble.ToString("F3");
                        }
                    }
            }
            ////// 計算結果をテキストボックスにセット
            return Json(new
            {
                status = "success",
                message = "計算処理が完了しました",
                winning = winningStr
            });
        }


        /// <summary>
        /// 勝率判定処理(Ajax)
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult WinAjax(Practice2ViewModel model)
        {
            string victoryString = model.Victory;
            string defeatString = model.Defeat;
            string drawString = model.Draw;
            string winningStr = "";

            //// 入力チェックを行う
            //// 入力チェック結果を取得
            string message = _service.InputCheck(victoryString, defeatString);
            if (!string.IsNullOrWhiteSpace(message))
            {
                // 処理結果がエラーであることとexceptionメッセージをJsonで返却
                return Json(new
                {
                    //status = "Error",
                    message = "入力してください"
                });
            }
            else
            {
                // 勝利数、敗戦数、引き分け数がゼロの場合、"-" を表示
                double victorydouble = double.Parse(model.Victory);
                double defeatdouble = double.Parse(model.Defeat);
                if (victorydouble == 0 && defeatdouble == 0 && defeatdouble == 0)
                {
                    winningStr = "-";
                    return Json(new
                    {
                        message = "試合数がありません",
                        winning = winningStr
                    });
                }
                else
                {
                    // 勝率を計算
                    double winningDouble = _service.WinPercentagealcalc(victorydouble, defeatdouble);

                    // 試合数があり、勝利数がゼロの場合
                    if (victorydouble == 0)
                    {
                        winningStr = ".000";
                        return Json(new
                        {
                            message = "まだ勝ちがありません",
                            winning = winningStr
                        });

                    }
                    else
                    {
                        //// 計算結果をテキストボックスにセット
                        winningStr = winningDouble.ToString("F3");
                        // 勝率5割未満の場合
                        if(winningDouble < 0.500)
                        return Json(new
                        {
                            message = "勝率5割以下です",
                            winning = winningStr
                        });
                        // 勝率5割以上,7割未満
                        if (winningDouble >=0.500 && winningDouble < 0.700)
                            return Json(new
                            {
                                message = "良い成績です",
                                winning = winningStr
                            });
                        // 勝率7割以上
                        if (winningDouble >= 0.700)
                            return Json(new
                            {
                                message = "すばらしい成績です",
                                winning = winningStr
                            });
                    }
                }
            }
            //}
            ////// 計算結果をテキストボックスにセット


            return Json(new
            {
                //message = "勝率判定",
                winning = winningStr
            });
        }


        /// <summary>
        /// 記録処理
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Record(Practice2ViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                //トランザクション開始

CLWebApp/CLWebApp/Views/Practice2/Index.cshtml
@{
    ViewData["Title"] = "橋本Practice";
}

<h2>@ViewData["Title"]</h2>

<ul>
    <li><a asp-area="" asp-controller="Practice2" asp-action="Winning">勝率計算</a></li>
    <li><a asp-area="" asp-controller="Practice2" asp-action="ParkingRecordCreate">駐車場データ</a></li>
</ul>

CLWebApp/CLWebApp/Views/Practice2/ParkingRecordCreate.cshtml
@using CLWebApp.Models.ViewModels
@model ParkingInfo

@{
    ViewData["Title"] = "駐車場データ";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <select asp-items="ViewBag.ParkInfo" id="ParkingInfoList" class="form-control input-sm" style="width: 300px;">
            <option value="">指定なし</option>
        </select>
    </div>

    <div class="row">
        <div class="form-group col-md-offset-5">
            <button type="submit" id="ajaxRecBtn" class="btn btn-success btn-lg col-md-offset-2 col-md-3">実行</button>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-offset-5">
            <button type="submit" id="minimumRateBtn" class="btn CalcProcessing btn-success btn-lg col-md-offset-2 col-md-3" data-btn="minBtn">最小</button>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-offset-5">
            <button type="submit" id="maxRateBtn" class="btn CalcProcessing btn-success btn-lg col-md-offset-2 col-md-3" data-btn="maxBtn">最大</button>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-offset-5">
            <button type="submit" id="averageRateBtn" class="btn CalcProcessing btn-success btn-lg col-md-offset-2 col-md-3" data-btn="aveBtn">平均</button>
        </div>
    </div>


    <form asp-action="ParkingRecordCreate" method="get">
        <div class="col-md-offset-5">
            <button type="submit" class="btn btn-warning">クリア</button>
        </div>
    </form>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group form-inline text-left">
                    <input class="form-control dataForm1" readonly />
                </div>
                <div class="form-group form-inline text-left">
                    <input class="form-control dataForm2" readonly />
                </div>
                <div class="form-group form-inline text-left">
                    <input class="form-control dataForm3" readonly />
                </div>
                <div class="form-group form-inline text-left">
                    <input class="form-control dataForm4" readonly />
                </div>
                <div class="form-group form-inline text-left">
                    <input class="form-control dataForm5" readonly />
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}
<script src="~/js/ParkingRecordCreate.js"></script>

CLWebApp/CLWebApp/Views/Practice2/Winning.cshtml
@using CLWebApp.Models.ViewModels
@model Practice2ViewModel
@{
    ViewData["Title"] = "勝率計算アプリ";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <form asp-action="Winning" method="get">
        <div class="col-md-offset-5">
            <button type="submit" class="btn btn-warning">クリア</button>
        </div>
    </form>

    <form asp-action="Calc" method="post" id="calcForm">
        <input type="hidden" asp-for="isCalculated" />

        @*<input type="hidden" asp-for="btnCalculationEnabled" />*@
        <div class="form-group form-inline col-md-12">
            <label asp-for="Victory" class="col-md-2 text-right"></label>
            <input asp-for="Victory" class="form-control col-md-3" maxlength="8" style="ime-mode: disabled" />
            <span asp-validation-for="Victory" class="text-danger col-md-7"></span>
        </div>
        <div class="form-group form-inline col-md-12">
            <label asp-for="Defeat" class="col-md-2 text-right"></label>
            <input asp-for="Defeat" class="form-control col-md-3" maxlength="8" style="ime-mode: disabled" />
            <span asp-validation-for="Defeat" class="text-danger col-md-7"></span>
        </div>
        <div class="form-group form-inline col-md-12">
            <label asp-for="Draw" class="col-md-2 text-right"></label>
            <input asp-for="Draw" class="form-control col-md-3" maxlength="8" style="ime-mode: disabled" />
            <span asp-validation-for="Draw" class="text-danger col-md-7"></span>
        </div>
        <div class="row">
            <div class="form-group form-inline col-md-12">
                <button type="submit" id="calcBtn" class="btn btn-success btn-lg col-md-offset-2 col-md-3">計算</button>
            </div>
        </div>

    </form>

    <div class="form-group form-inline col-md-12">
        <label asp-for="Winning" class="col-md-2 text-right"></label>
        <input asp-for="Winning" class="form-control col-md-3" readonly />
    </div>

    <div class="row">
        <div class="form-group form-inline col-md-5">
            <button type="button" id="calcAjaxBtn" class="btn btn-primary btn-xs col-md-offset-2 col-md-3">計算(Ajax)</button>
        </div>
    </div>
    <div class="row">
        <div class="form-group form-inline col-md-5">
            <button type="button" id="winAjaxBtn" class="btn btn-basic btn-xs col-md-offset-2 col-md-3">勝率判定(Ajax)</button>
        </div>
    </div>
    <form asp-action="Record" method="post">
        <div class="form-group">
            <button type="submit" class="submit_button btn btn-danger" id="recBtn">記録</button>
        </div>
    </form>

    <div class="form-group form-inline col-md-12">
        <form asp-controller="Average" asp-action="Index">
            <div class="col-md-offset-5">
                <button type="submit" class="btn btn-xs btn-info glyphicon glyphicon-bold">打率計算アプリ</button>
            </div>
        </form>
    </div>

    <div class="form-group form-inline col-md-12">
        <form asp-controller="Practice2" asp-action="Index">
            <div class="col-md-offset-5">
                <button type="submit" class="btn btn-xs btn-default">橋本Practiceに戻る</button>
            </div>
        </form>
    </div>

    <div class="form-group form-inline col-md-12">
        <form asp-controller="Home" asp-action="Index">
            <div class="col-md-offset-5">
                <button type="submit" class="btn btn-primary">ホームに戻る</button>
            </div>
        </form>
    </div>

</div>

    @section Scripts {
        @await Html.PartialAsync("_ValidationScriptsPartial")
    }
    <script src="~/js/Practice2.js"></script>