CLWebApp/CLWebApp/Models/ViewModels/Practice1ViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CLWebApp.Models.ViewModels
{
    public class Practice1ViewModel
    {

        /// <summary>
        /// 計測日
        /// </summary>
        [Required(ErrorMessage = "測定日時を入力してください")]
        [Display(Name = "測定日時：")]
        public string measuringdate { get; set; }

        [Range(0.01, 3.00, ErrorMessage = "身長は0より大きい数値(最大：3.00)、入力してください")]
        [Required(ErrorMessage = "身長を入力してください")]
        [Display(Name = "身長(m)：")]
        public string height { get; set; }

        [Range(0.1, 999.9, ErrorMessage = "体重は0より大きい数値(最大：999.9)で入力してください")]
        [Required(ErrorMessage = "体重を入力してください")]
        [Display(Name = "体重(kg)：")]
        public string weight { get; set; }

        [Display(Name = "BMI：")]
        public string bmi { get; set; }

        /// <summary>
        /// 計算ボタンクリック状態管理
        /// </summary>
        public bool btnCalculationEnabled { get; set; }

        /// <summary>
        /// 診断結果ボタンクリック状態管理
        /// </summary>
        public bool btnResultEnabled { get; set; }

        /// <summary>
        /// 計算完了判定
        /// </summary>
        public bool isCalculated { get; set; }

    }
}

CLWebApp/CLWebApp/Models/ViewModels/ResultViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CLWebApp.Models.ViewModels
{
    public class ResultViewModel
    {

        [Display(Name = "あなたのBMI:")]
        public string yourbmi { get; set; }

        [Display(Name = "あなたの診断結果")]
        public string diagnosis { get; set; }

    }
}

CLWebApp/CLWebApp/Controllers/Practice1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CLWebApp.Data;
using CLWebApp.Models;
using CLWebApp.Models.ViewModels;
using CLWebApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CLWebApp.Controllers
{
    public class Practice1Controller : CLBaseController
    {
        // 宣言
        private readonly ApplicationDbContext _context;
        private Practice1Service _service;
        private List<ParkingInfo> _parkingList;

        /// <summary>
        /// コンストラクター
        /// </summary>
        public Practice1Controller(ApplicationDbContext context)
        {
            // 初期化
            _service = new Practice1Service();
            _context = context;
            // _parkingListにマスターデータを読み込む
            _parkingList = _context.ParkingInfos.ToList();
        }


        /// <summary>
        /// BMI計算ページ
        /// </summary>
        /// <returns></returns>
        public IActionResult Bmi()
        {
            // 宣言して初期化
            Practice1ViewModel model = new Practice1ViewModel();
            _service.Clear(model);

            return View(model);
        }


        /// <summary>
        /// Indexページ(橋詰練習)
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// 計算処理
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Calc(Practice1ViewModel model)
        {
            if (ModelState.IsValid)
            {
                // POST後の画面再描画のため状態をクリア
                ModelState.Clear();

                double heightDouble = double.Parse(model.height);
                double weightDouble = double.Parse(model.weight);
                double bmi = _service.CalcBmi(heightDouble, weightDouble);

                model.bmi = bmi.ToString();

                //model.btnCalculationEnabled = true;
                model.isCalculated = true;
            }
            return View("Bmi", model);
        }

        /// <summary>
        /// 計算処理(Ajax)
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult CalcAjax(Practice1ViewModel model)
        {
                double heightDouble = double.Parse(model.height);
                double weightDouble = double.Parse(model.weight);
                double bmi = _service.CalcBmi(heightDouble, weightDouble);

            // BMIの値をstring型へ変換
            var bmiStr = bmi.ToString();

            return Json(new
            {
                //計算結果とhiddenの値を返す
                status = "success",
                result = bmiStr,
                hiddenCalc = false,
                hiddenRec = true
            });
        }


        /// <summary>
        /// 記録処理
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Record(Practice1ViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                //トランザクション開始
                using (var transaction = _context.Database.BeginTransaction())
                {
                    try
                    {
                    BmiRecord model = new BmiRecord();

                        // 記録処理を記述              
                        // ログイン中のユーザー情報をとる
                        //string userName = User.Identity.Name;
                        //var user = _context.Users.Where(p => p.UserName.Equals(userName)).First();
                        var user = GetLoginUser(_context);
                        // viewModelからModelに値を渡す
                        model.User = user;
                        model.BmiDate = DateTime.Parse(viewModel.measuringdate);
                        model.Height = double.Parse(viewModel.height);
                        model.Weight = double.Parse(viewModel.weight);
                        model.Bmi = double.Parse(viewModel.bmi);

                        // 引数に指定したエンティティをデータベースに追加
                        _context.Add(model);

                        // データベースに変更が反映
                        _context.SaveChanges();

                        // データベースの更新内容が有効
                        transaction.Commit();

                        // Bmiに戻る
                        return RedirectToAction(nameof(Bmi));
                    }
                    catch (Exception ex)
                    {
                        // データベースの更新内容が無効
                        transaction.Rollback();

                        //上部にエラーを赤文字で表示
                        ModelState.AddModelError(string.Empty, "エラーが発生しました。");                      
                    }
                }
            }
            return View("Bmi", viewModel);
        }

        /// <summary>
		/// 記録処理(Ajax)
		/// </summary>
		/// <param name="viewModel"></param>
		/// <returns></returns>
		[HttpPost]
        public IActionResult RecordAjax(Practice1ViewModel viewModel)
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    // ログイン中のユーザー情報
                    var user = GetLoginUser(_context);

                    // 追加する燃費レコードのモデルを作成
                    BmiRecord model = new BmiRecord();
                    model.User = user;
                    model.BmiDate = DateTime.Parse(viewModel.measuringdate);
                    model.Height = double.Parse(viewModel.height);
                    model.Weight = double.Parse(viewModel.weight);
                    model.Bmi = double.Parse(viewModel.bmi);

                    // コンテキストに追加
                    _context.Add(model);
                    _context.SaveChanges();
                    transaction.Commit();
                }
                catch (Exception ex)
                {
                    // 処理結果がエラーであることとexceptionメッセージをJsonで返却
                    return Json(new
                    {
                        status = "dbError",
                        message = $"記録処理でエラーが発生しました\r\n({ex.Message})"
                    });
                }
            }

            // 処理結果が成功であることとメッセージをJsonで返却
            return Json(new
            {
                status = "success",
                message = "記録処理が完了しました"
            });
        }

        /// <summary>
        /// 診断結果
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Result(Practice1ViewModel model)
        {
            // ResultViewModelのインスタンス生成
            ResultViewModel resultViewModel = new ResultViewModel();
            // Practice1の値をResultに当てはめる
            resultViewModel.yourbmi = model.bmi;
            // 値を渡す
            return View(resultViewModel);
        }


        // GET: BmiRecords
        /// <summary>
        /// BMIリストページ
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> BmiList()
        {
            return View(await _context.BmiRecords.ToListAsync());
        }

        /// <summary>
        /// Parkingリストページ
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> ParkingData()
        {
            // 初期化
            //_parkingList = new List<ParkingInfo>();←手動でするので初期化必要ない？

            //_parkingListにマスターデータを読み込む　
            //_parkingList = await _context.ParkingInfos.ToListAsync();
            //　※↑ここに記述すると次のリクエスト時に値が空になるのでコンストラクタ内に記述する

            //_parkingListを加工(パーキング名順、Idとパーキング名をセレクト)、
            var _parking = _parkingList.OrderBy(c => c.ParkingName).Select(x => new { Id = x.Id, Value = x.ParkingName });
            // ViewBagに画面リスト用データをセット
            ViewBag.Parking = new SelectList(_parking, "Id", "Value");
            return View();
        }

        /// <summary>
        /// 読み込み(Parkingリスト)
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        //[HttpPost]
        public async Task<IActionResult> SelectData(long? id)
        {
            // _parkingListからパラメータのIdを使ってデータを一件取得する(マスメンのEdit,Delete参考)
            // idがnullの時
            if (id == null)
            {
                return NotFound();
            }

            // _parkingListから_parkingListのIdとドロップダウンで選択したidが同じのデータを取得
            var parkingInfo = _parkingList.Find(_ => _.Id == id);

            // parkingInfoがnullの時
            if (parkingInfo == null)
            {
                return NotFound();
            }

            //JSONで、リストから取得したデータを返す
            return Json(new
            {
                status = "success",
                pInfo = parkingInfo,
            });
        }

        [HttpPost]
        public async Task<IActionResult> StudyLinq(long? bt)
        {
            // parkingInfoを使うためnew
            var parkingInfo = new ParkingInfo();

            //btがnullの時
            if (bt == null)
            {
                return NotFound();
            }

            if (bt == 1)
            {
                //TimeRate最小(リストから取り出す)
                var timeRateMin = _parkingList.Min(x => x.TimeRate);
                parkingInfo = _parkingList.Find(x => x.TimeRate == timeRateMin);
            }
            else if (bt == 2)
            {
                // MaxFee最大a(リストから取り出す)
                parkingInfo = _parkingList.OrderByDescending(x => x.MaxFee).First();
                //// MaxFee最大b
                //var maxFeeMax = _parkingList.Max(x => x.MaxFee);
                //var parkingInfo = _parkingList.Find(x => x.MaxFee == parkingInfo);
            }
            else if (bt == 3)
            {
                //平均(リストから取り出す)
                var TimeRateAve = _parkingList.Average(x => x.TimeRate);

CLWebApp/CLWebApp/Views/practice1/Bmi.cshtml
@using CLWebApp.Models.ViewModels
@model Practice1ViewModel
@{
    ViewData["Title"] = "BMI計算";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <form asp-action="Bmi" method="get">
        <div class="col-md-offset-5">
            <button type="submit" class="btn btn-warning">クリア</button>
        </div>
    </form>

    <form method="post">
        <input type="hidden" asp-for="btnCalculationEnabled" />
        <div class="form-group form-inline col-md-12">
            <label asp-for="measuringdate" class="col-md-2 text-right"></label>
            <input asp-for="measuringdate" type="text" class="jqdatetimepicker">
            <span asp-validation-for="measuringdate" class="text-danger"></span>
        </div>
        <div class="form-group form-inline col-md-12">
            <label asp-for="height" class="col-md-2 text-right"></label>
            <input asp-for="height" />
            <span asp-validation-for="height" class="text-danger"></span>
        </div>
        <div class="form-group form-inline col-md-12">
            <label asp-for="weight" class="col-md-2 text-right"></label>
            <input asp-for="weight" />
            <span asp-validation-for="weight" class="text-danger"></span>
        </div>
        <div class="form-group form-inline col-md-12">
            <button type="button" class="submit_button btn btn-success btn-md col-md-offset-2 col-md-2" data-action="@Url.Action("Calc","Practice1")" id="calcBtn" data-btn="calcBtn" );">計算</button>
        </div>
        <div class="form-group form-inline col-md-12">
            <button type="button" class="btn btn-primary btn-md col-md-offset-2 col-md-2" id="ajaxCalcBtn" data-btn="ajaxCalcBtn">計算(ajax)</button>
        </div>
        <input type="hidden" asp-for="isCalculated" />
        <div class="form-group form-inline col-md-12">
            <label asp-for="bmi" class="col-md-2 text-right"></label>
            <input asp-for="bmi" readonly />
        </div>
        <div class="form-group">
            <button type="button" class="submit_button btn btn-danger" data-action="@Url.Action("Record","Practice1")" data-btn="recBtn">記録</button>
        </div>
        <div class="form-group">
            <button type="button" class="submit_button btn btn-primary" id="ajaxRecBtn" data-btn="ajaxRecBtn">記録(ajax)</button>
        </div>
    </form>

    <form asp-controller="Practice1" asp-action="BmiList">
        <div class="form-group">
            <button type="submit" class="btn btn-default">記録一覧</button>
        </div>
    </form>

    <form asp-action="Result" method="post">
        <input type="hidden" asp-for="bmi" />
        <div class="form-group form-inline col-md-12">
            <button type="submit" class="btn btn-info btn-md col-md-offset-2 col-md-2" id="ResBtn">診断結果</button>
        </div>
    </form>

    <form asp-controller="Practice1" asp-action="Index">
        <div class="form-group col-md-offset-5">
            <button type="submit" class="btn btn-default">橋詰練習に戻る</button>
        </div>
    </form>

    <form asp-controller="Home" asp-action="Index">
        <div class="form-group col-md-offset-5">
            <button type="submit" class="btn btn-primary">ホームに戻る</button>
        </div>
    </form>

</div>
    @section Scripts {
        @await Html.PartialAsync("_ValidationScriptsPartial")
    }
    <script src="~/js/Practice1.js"></script>

CLWebApp/CLWebApp/Views/practice1/BmiList.cshtml
@model IEnumerable<CLWebApp.Models.BmiRecord>

@{
    ViewData["Title"] = "BMI計測一覧";
}

<h2>BMI計測一覧</h2>

@*<p>
        <a asp-action="Create">Create New</a>
    </p>*@
<table class="table table-striped table-hover table-striped table-condensed table-bordered" id="bmi-table">
    <thead class="info">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BmiDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bmi)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BmiDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Height)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bmi)
                </td>
                <td>
                    @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>

<table border="1" align="center" @*class="table" *@>
    <tr>
        <th>BMI（数値の範囲）</th>
        <th>肥満度の判定</th>
    </tr>
    <tr>
        <td>18.5未満</td>
        <td>普通体重</td>
    </tr>
    <tr>
        <td>25以上30未満</td>
        <td>肥満（1度）</td>
    </tr>
    <tr>
        <td>25以上30未満</td>
        <td>肥満（1度）</td>
    </tr>
    <tr>
        <td>30以上35未満</td>
        <td>肥満（2度）</td>
    </tr>
    <tr>
        <td>35以上40未満</td>
        <td>肥満（3度）</td>
    </tr>
    <tr class="danger">
        <td>40以上</td>
        <td>肥満（4度）</td>
    </tr>
</table>

<script>
    // DataTables使用
    $(document).ready(function () {
        $('#bmi-table').DataTable();
    });
</script>

CLWebApp/CLWebApp/Views/practice1/Index.cshtml
@{
    ViewData["Title"] = "橋詰練習";
}

<h2>橋詰練習</h2>
<ul>
    <li><a asp-area="" asp-controller="Practice1" asp-action="Bmi">BMI計算</a></li>
    <li><a asp-area="" asp-controller="Practice1" asp-action="ParkingData">ParkingData</a></li>
</ul>

CLWebApp/CLWebApp/Views/practice1/ParkingData.cshtml
@model CLWebApp.Models.ParkingInfo
@{
    ViewData["Title"] = "Parkingデータ";
}

<h2>Parkingデータ</h2>

<form asp-action="ParkingData" method="get">
    <div class="form-group">
        <label asp-for="ParkingName" class="control-label"></label>
        <select asp-items="ViewBag.Parking" id="ParkingSelect" asp-for="ParkingName" class="form-control input-sm" style="width: 300px;">
            <option value="">指定なし</option>
        </select>
        <span asp-validation-for="ParkingName" class="text-danger"></span>
    </div>

    <div class="form-group col-md-offset-5">
        <button type="submit" class="btn btn-warning">クリア</button>
    </div>
</form>

<div class="form-group">
    <div class="col-md-offset-5">
        <button type="submit" class="btn btn-primary" id="execBtn">読み込み</button>
    </div>
    <div class="col-md-offset-5">
        <button type="submit" class="study-linq btn btn-primary" data-btn="1">TimeRate最小</button>
    </div>
    <div class="col-md-offset-5">
        <button type="submit" class="study-linq btn btn-primary" data-btn="2">MaxFee最大</button>
    </div>
    <div class="col-md-offset-5">
        <button type="submit" class="study-linq btn btn-primary" data-btn="3">平均</button>
    </div>
</div>

    <div style="display:inline-flex">
        <p>
            パーキング名<br>
            <input type="text" id="parkingName">
        <p>
            分あたり<br>
            <input type="text" id="timeRate">
        <p>
            円<br>
            <input type="text" id="fee">
        <p>
            最大料金<br>
            <input type="text" id="maxFee">
        <p>
            場所<br>
            <input type="text" id="location">
        <p>
    </div>




    <script src="~/js/ParkingData.js"></script>

CLWebApp/CLWebApp/Views/practice1/Result.cshtml
@using CLWebApp.Models.ViewModels
@model ResultViewModel
@{
    ViewData["Title"] = "診断結果";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Practice1" asp-action="Bmi">
    <div class="form-group col-md-offset-5">
        <button type="submit" class="btn btn-default rounded-0">BMI計算に戻る</button>
    </div>
</form>

<div class="form-group form-inline col-md-12">
    <label asp-for="yourbmi" class="col-md-2 text-right"></label>
    <input asp-for="yourbmi" class="form-control col-md-3" maxlength="6" style ="background-color:#ffffff;" readonly />
</div>

<div class="form-group form-inline col-md-12">
    <label asp-for="diagnosis" class="col-md-2 text-right"></label>
    <textarea asp-for="diagnosis" class="form-control col-md-3" maxlength="6" style ="background-color:#ffffff;" readonly></textarea>
</div>

<form asp-controller="Home" asp-action="Index">
    <div class="form-group col-md-offset-5">
        <button type="submit" class="btn btn-primary">ホームに戻る</button>
    </div>
</form>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}
<script src="~/js/Result.js"></script>