CLWebApp/CLWebApp/Models/ViewModels/NenpiViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CLWebApp.Models.ViewModels
{
    //[CustomValidation(typeof(NenpiViewModel), "CheckCurrentMileage")]

    /// <summary>
    /// 燃費計算画面ViewModel
    /// </summary>
    public class NenpiViewModel : IValidatableObject
    {

        /// <summary>
        /// 給油日
        /// </summary>
        [Required(ErrorMessage = "給油日を入力してください")]
        [Display(Name = "給油日：")]
        public string dataTimePicker { get; set; }

        /// <summary>
        /// 給油量
        /// </summary>
        [Required(ErrorMessage = "給油量を入力してください")]
        [RegularExpression(@"^\d{1,3}(\.\d)?$", ErrorMessage = "給油量は正の数値(小数点以下一桁まで)で入力してください")]
        [Display(Name = "給油量：")]
        public string boxOilingQuantity { get; set; }

        /// <summary>
        /// 前回給油時走行距離
        /// </summary>
        [Display(Name = "前回給油時走行距離：")]
        public string pastMileage { get; set; }

        /// <summary>
        /// 給油時走行距離
        /// </summary>
		[Range(0.1, 9999999.9, ErrorMessage = "給油時走行距離は0より大きい数値(最大：9999999.9)で入力してください")]
		[RegularExpression(@"^\d{1,7}(\.\d)?$", ErrorMessage = "給油時走行距離は正の数値(小数点以下一桁まで)で入力してください")]
		[Display(Name = "給油時走行距離：")]
        public string currentMileage { get; set; }

        /// <summary>
        /// 区間走行距離
        /// </summary>
        [Display(Name = "区間走行距離：")]
        public string thisMileage { get; set; }

        /// <summary>
        /// 区間燃費
        /// </summary>
        //[Required(ErrorMessage = "記録処理は区間燃費の算出後に実行してください")]
        [Display(Name = "区間燃費：")]
        public string fuelConsumption { get; set; }

        /// <summary>
        /// 計算ボタンクリック状態管理
        /// </summary>
        public bool btnCalculationEnabled { get; set; }

        /// <summary>
        /// 計算完了判定
        /// </summary>
        public bool isCalculated { get; set; }

        //給油時走行距離入力チェックメソッド
        //public static ValidationResult CheckCurrentMileage(NenpiViewModel model)
        //{
        //    if (double.Parse(model.currentMileage) == 0)
        //    {
        //        return new ValidationResult("給油時走行距離は0より大きい数値で入力してください");
        //    }
        //    if (double.Parse(model.currentMileage) <= double.Parse(model.pastMileage))
        //    {
        //        return new ValidationResult("給油時総走行距離は前回の距離より大きな値で入力してください");
        //    }

        //    return ValidationResult.Success;
        //}

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (double.Parse(currentMileage) == 0)
            {
                yield return new ValidationResult("給油時走行距離は0より大きい数値で入力してください", new[] { "currentMileage" });
            }
            if (double.Parse(currentMileage) <= double.Parse(pastMileage))
            {
                yield return new ValidationResult("給油時総走行距離は前回の距離より大きな値で入力してください", new[] { "currentMileage" });
            }
        }

    }
}

CLWebApp/CLWebApp/Controllers/NenpiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CLWebApp.Data;
using CLWebApp.Models;
using CLWebApp.Models.ViewModels;
using CLWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CLWebApp.Controllers
{

    /// <summary>
    /// 燃費計算画面コントローラー
    /// </summary>
    [Authorize]
    public class NenpiController : CLBaseController
    {
        private readonly ApplicationDbContext _context;
        private NenpiService _service;


        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="context">DBコンテキスト</param>
        public NenpiController(ApplicationDbContext context)
        {
            _service = new NenpiService();
            // コンテキストDI
            _context = context;
        }

        public IActionResult Index()
        {
            // ログイン中のユーザー情報
            var user = GetLoginUser(_context);

            NenpiViewModel model = new NenpiViewModel();

            // 画面初期化
            _service.Clear(model, _context, user);

            return View(model);
        }


        /// <summary>
        /// 計算処理
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Calc(NenpiViewModel model)
        {
            if (ModelState.IsValid)
            {
                // POST後の画面再描画のため状態をクリア
                ModelState.Clear();

                string oiling = model.boxOilingQuantity;
                string mileageVal = model.thisMileage;

                /////1.給油量の入力チェックを行う
                //// 入力チェック結果を取得
                string message = _service.CheckOilingQuantity(oiling);
                if (!string.IsNullOrWhiteSpace(message))
                {
                    // エラーの場合
                    ModelState.AddModelError(string.Empty, message);
                }
                else
                {
                    /////2-1.燃費計算
                    /////区間燃費 ＝ 区間距離 / 給油量
                    double oilingdouble = double.Parse(model.boxOilingQuantity);
                    double valThisMileage = double.Parse(model.currentMileage);
                    double nenpi = _service.Culcnenpi(oilingdouble, valThisMileage);

                    //// 3.燃費計算結果をテキストボックスにセット
                    model.fuelConsumption = nenpi.ToString("#0.0");

                    /////4.「クリア」「記録」「終了」ボタン以外の入力部品を変更不可状態にする。   
                    model.isCalculated = true;
                }
            }

            return View("Index", model);
        }

        /// <summary>
        /// 記録処理
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Record(NenpiViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = _context.Database.BeginTransaction())
                {
                    try
                    {
                        // ログイン中のユーザー情報
                        var user = GetLoginUser(_context);

                        // 追加する燃費レコードのモデルを作成
                        NenpiRecord model = new NenpiRecord();
                        model.RefuelDate = DateTime.Parse(viewModel.dataTimePicker);
                        model.Mileage = double.Parse(viewModel.currentMileage);
                        model.TripMileage = double.Parse(viewModel.thisMileage);
                        model.FuelCost = Double.Parse(viewModel.fuelConsumption);
                        model.User = user;

                        // コンテキストに追加
                        _context.Add(model);
                        _context.SaveChanges();
                        transaction.Commit();

                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                        //_context.RevertChanges();
                        ModelState.AddModelError(string.Empty, "エラーが発生しました。");
                    }
                }
            }

            return View("Index", viewModel);
        }

		/// <summary>
		/// 記録処理(Ajax)
		/// </summary>
		/// <param name="viewModel"></param>
		/// <returns></returns>
		[HttpPost]
		public IActionResult RecordAjax(NenpiViewModel viewModel)
		{
			using (var transaction = _context.Database.BeginTransaction())
			{
				try
				{
                    // ログイン中のユーザー情報
                    var user = GetLoginUser(_context);

                    // 追加する燃費レコードのモデルを作成
                    NenpiRecord model = new NenpiRecord();
					model.RefuelDate = DateTime.Parse(viewModel.dataTimePicker);
					model.Mileage = double.Parse(viewModel.currentMileage);
					model.TripMileage = double.Parse(viewModel.thisMileage);
					model.FuelCost = Double.Parse(viewModel.fuelConsumption);
					model.User = user;

					// コンテキストに追加
					_context.Add(model);
					_context.SaveChanges();
					transaction.Commit();
				}
				catch (Exception ex)
				{
					// 処理結果がエラーであることとexceptionメッセージをJsonで返却
					return Json(new
					{
						status = "dbError",
						message = $"記録処理でエラーが発生しました\r\n({ex.Message})"
					});
				}
			}

			// 処理結果が成功であることとメッセージをJsonで返却
			return Json(new
			{
				status = "success",
				message = "記録処理が完了しました"
			});
		}
	}
}

CLWebApp/CLWebApp/Views/Nenpi/Index.cshtml
@using CLWebApp.Models.ViewModels
@model NenpiViewModel
@{
    ViewData["Title"] = "燃費計算アプリ";
}

<h2>@ViewData["Title"]</h2>


<div class="row">
    @*<div class="col-md-8">*@
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <form asp-action="Index" method="get">
        <div class="col-md-offset-5">
            <button type="submit" class="btn btn-warning">クリア</button>
        </div>
    </form>
    <form method="post">
        <input type="hidden" asp-for="btnCalculationEnabled" />
        <input type="hidden" asp-for="isCalculated" />
        <div class="form-group form-inline col-md-12">
            <label asp-for="dataTimePicker" class="col-md-2 text-right"></label>
            <input type="text" asp-for="dataTimePicker" class="form-control col-md-3 datepicker" />
            <span asp-validation-for="dataTimePicker" class="text-danger col-md-7"></span>
        </div>
        <div class="form-group form-inline col-md-12">
            <label asp-for="boxOilingQuantity" class="col-md-2 text-right"></label>
            <input asp-for="boxOilingQuantity" class="form-control col-md-3" maxlength="5" style="ime-mode: disabled" />
            <span asp-validation-for="boxOilingQuantity" class="text-danger col-md-7"></span>
        </div>
        <div class="form-group form-inline col-md-12">
            <label asp-for="pastMileage" class="col-md-2 text-right"></label>
            <input asp-for="pastMileage" class="form-control col-md-3" readonly />
        </div>
        <div class="form-group form-inline col-md-12">
            <label asp-for="currentMileage" class="col-md-2 text-right"></label>
            <input asp-for="currentMileage" class="form-control col-md-3" maxlength="9" style="ime-mode: disabled" />
            <span asp-validation-for="currentMileage" class="text-danger col-md-7"></span>
        </div>
        <div class="form-group form-inline col-md-12">
            <label asp-for="thisMileage" class="col-md-2 text-right"></label>
            <input asp-for="thisMileage" class="form-control col-md-3" readonly />
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <button type="button" class="submit_button btn btn-success btn-lg col-md-offset-2 col-md-3" id="calcBtn" data-action="@Url.Action("Calc","Nenpi")" data-btn="calcBtn">計算</button>
            </div>
        </div>
        <div class="form-group form-inline col-md-12">
            <label asp-for="fuelConsumption" class="col-md-2 text-right"></label>
            <input asp-for="fuelConsumption" class="form-control col-md-3 " readonly />
            <span asp-validation-for="fuelConsumption" class="text-danger col-md-7"></span>
        </div>
        <div class="form-group">
            <button type="button" class="submit_button btn btn-danger" id="recBtn" data-action="@Url.Action("Record","Nenpi")" data-btn="recBtn">記録</button>
        </div>
        <div class="form-group">
            <button type="button" class="submit_button btn btn-primary" id="ajaxRecBtn" data-btn="ajaxRecBtn">記録(ajax)</button>
        </div>
    </form>
    <form asp-controller="Home" asp-action="Index">
        <div class="col-md-offset-5">
            <button type="submit" class="btn btn-primary">ホームに戻る</button>
        </div>
    </form>
    @*</div>
        <div class="col-md-4"></div>*@
</div>


@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}
<script src="~/js/Nenpi.js"></script>